#!/usr/bin/env python3
"""Regenerate references/widget-catalog.md from the published widget packages.

The catalog is what an agent reads to CHOOSE widgets. It is built from each
widget's `src/definition-schema.json` (its `description` and `aiSelection`
block) at the version currently tagged `latest` on npm, so it says exactly what
the widget authors wrote for agents. Exact property names are not copied here on
purpose: they change with widget releases, and scripts/widget.py reads them live.

Run after a widget is added, removed or its aiSelection text changes:

    python3 tools/build_widget_catalog.py

Standard library only; reuses the skill's scripts/widget.py for fetching.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILL = REPO / "plugins/ironflock/skills/ironflock-templates"
OUT = SKILL / "references/widget-catalog.md"

sys.path.insert(0, str(SKILL / "scripts"))
from widget import latest_version, load_schema  # noqa: E402  (the skill's own fetch + cache)

# The widgets the platform registers, grouped the way the public widget
# reference groups them. A package missing here is not offered to agents.
CATEGORIES: list[tuple[str, list[str]]] = [
    (
        "Data visualization",
        [
            "widget-linechart",
            "widget-value",
            "widget-gauge",
            "widget-signal",
            "widget-doughnut",
            "widget-table",
            "widget-heatmap",
            "widget-statehistory",
            "widget-mapbox",
            "widget-scada",
        ],
    ),
    (
        "Content and media",
        [
            "widget-label",
            "widget-textbox",
            "widget-markdown",
            "widget-image",
            "widget-overlay",
            "widget-embed",
        ],
    ),
    (
        "Input and control",
        ["widget-form", "widget-switch", "widget-filter-dropdown", "widget-filter-calendar"],
    ),
    ("Navigation", ["widget-navbar", "widget-sidenav", "widget-navbutton"]),
    ("Notifications", ["widget-toast"]),
]

def first_sentences(text: str, limit: int = 2) -> str:
    parts = re.split(r"(?<=[.!?])\s+", " ".join(text.split()))
    return " ".join(parts[:limit])


def render(pkg: str, schema: dict) -> str:
    sel = schema.get("aiSelection") or {}
    lines = [f"### {pkg}", "", first_sentences(schema.get("description", ""))]
    if sel.get("dataShape"):
        lines += ["", f"**Data shape:** {' '.join(sel['dataShape'].split())}"]
    if sel.get("useWhen"):
        lines += ["", "**Use when:**"] + [f"- {' '.join(u.split())}" for u in sel["useWhen"]]
    if sel.get("notFor"):
        lines += ["", "**Not for:**"] + [f"- {' '.join(n.split())}" for n in sel["notFor"]]
    return "\n".join(lines)


def main() -> int:
    sections = []
    for title, packages in CATEGORIES:
        body = []
        for pkg in packages:
            version, schema = load_schema(pkg, latest_version(pkg))
            body.append(render(pkg, schema))
            print(f"{pkg}@{version}", file=sys.stderr)
        sections.append(f"## {title}\n\n" + "\n\n".join(body))

    OUT.write_text(
        "# Widget catalog\n\n"
        "Generated by `tools/build_widget_catalog.py` from each widget's published\n"
        "`definition-schema.json` (`description` + `aiSelection`). Do not edit by hand.\n\n"
        "Use this file to choose widgets. Then read the chosen widget's real schema with\n"
        "`scripts/widget.py <package>` before writing its `chartconfig` — property names\n"
        "are not listed here because they change with widget releases.\n\n"
        "## Contents\n\n"
        + "\n".join(f"- {t}: " + ", ".join(p for p in pk) for t, pk in CATEGORIES)
        + "\n\n"
        + "\n\n".join(sections)
        + "\n"
    )
    print(f"wrote {OUT.relative_to(REPO)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
